"""BoardType name unique, code must

Revision ID: 1b82f727b011
Revises: 594ed577ffcc
Create Date: 2022-05-29 22:58:55.415633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b82f727b011'
down_revision = '594ed577ffcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('board_types', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.create_index(op.f('ix_board_types_name'), 'board_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_types_name'), table_name='board_types')
    op.alter_column('board_types', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('board_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
