"""lazy joined

Revision ID: 245dc034505e
Revises: 1b82f727b011
Create Date: 2022-05-29 23:01:18.354187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245dc034505e'
down_revision = '1b82f727b011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
