"""new model FacilityGroup, Room, Amenity, Image, Hotel, BoardType, Address

Revision ID: 594ed577ffcc
Revises: c934858edce1
Create Date: 2022-05-26 14:48:37.541689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "594ed577ffcc"
down_revision = "c934858edce1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("code", sa.String(length=5), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "facilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("tag", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tax", sa.Integer(), nullable=True),
        sa.Column("service_charge", sa.Integer(), nullable=True),
        sa.Column("partnership_discount", sa.Float(), nullable=True),
        sa.Column("discount_promo_code", sa.String(length=20), nullable=True),
        sa.Column("discount_description", sa.String(length=150), nullable=True),
        sa.Column("rating_value", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hotels_name"), "hotels", ["name"], unique=True)
    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("street_address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "facility_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("breakfast", sa.Boolean(), nullable=True),
        sa.Column("restaurant", sa.Boolean(), nullable=True),
        sa.Column("parking", sa.Boolean(), nullable=True),
        sa.Column("two_four_security", sa.Boolean(), nullable=True),
        sa.Column("business", sa.Boolean(), nullable=True),
        sa.Column("swimming_pool", sa.Boolean(), nullable=True),
        sa.Column("room_service", sa.Boolean(), nullable=True),
        sa.Column("indoor_games", sa.Boolean(), nullable=True),
        sa.Column("outdoor_activities", sa.Boolean(), nullable=True),
        sa.Column("fitness_centre", sa.Boolean(), nullable=True),
        sa.Column("airport_shuttle", sa.Boolean(), nullable=True),
        sa.Column("early_checkin", sa.Boolean(), nullable=True),
        sa.Column("late_checkout", sa.Boolean(), nullable=True),
        sa.Column("air_conditioning", sa.Boolean(), nullable=True),
        sa.Column("kid_friendly", sa.Boolean(), nullable=True),
        sa.Column("couple_friendly", sa.Boolean(), nullable=True),
        sa.Column("disability_friendly", sa.Boolean(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("adult", sa.Integer(), nullable=True),
        sa.Column("child", sa.Integer(), nullable=True),
        sa.Column("extra_bed", sa.Integer(), nullable=True),
        sa.Column("max_occupancies", sa.Integer(), nullable=True),
        sa.Column("available_room", sa.Integer(), nullable=True),
        sa.Column("rate", sa.Integer(), nullable=True),
        sa.Column("board_type_id", sa.Integer(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["board_type_id"], ["board_types.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "amenities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("air_conditioning", sa.Boolean(), nullable=True),
        sa.Column("balcony", sa.Boolean(), nullable=True),
        sa.Column("bathtub", sa.Boolean(), nullable=True),
        sa.Column("ceiling_fan", sa.Boolean(), nullable=True),
        sa.Column("clothes_dryer", sa.Boolean(), nullable=True),
        sa.Column("connecting_rooms", sa.Boolean(), nullable=True),
        sa.Column("cooker", sa.Boolean(), nullable=True),
        sa.Column("dining_area", sa.Boolean(), nullable=True),
        sa.Column("disability_friendly", sa.Boolean(), nullable=True),
        sa.Column("electric_kettle", sa.Boolean(), nullable=True),
        sa.Column("garden_view", sa.Boolean(), nullable=True),
        sa.Column("hairdryer", sa.Boolean(), nullable=True),
        sa.Column("hot_water", sa.Boolean(), nullable=True),
        sa.Column("ironing_set", sa.Boolean(), nullable=True),
        sa.Column("kitchenete", sa.Boolean(), nullable=True),
        sa.Column("microwave_oven", sa.Boolean(), nullable=True),
        sa.Column("minibar", sa.Boolean(), nullable=True),
        sa.Column("mountain_or_hill_view", sa.Boolean(), nullable=True),
        sa.Column("non_smoking_room", sa.Boolean(), nullable=True),
        sa.Column("pool_view", sa.Boolean(), nullable=True),
        sa.Column("power_outlet", sa.Boolean(), nullable=True),
        sa.Column("private_beach", sa.Boolean(), nullable=True),
        sa.Column("safe_or_locker", sa.Boolean(), nullable=True),
        sa.Column("smoking_room", sa.Boolean(), nullable=True),
        sa.Column("tea_and_offee", sa.Boolean(), nullable=True),
        sa.Column("telephone", sa.Boolean(), nullable=True),
        sa.Column("toiletries", sa.Boolean(), nullable=True),
        sa.Column("tv", sa.Boolean(), nullable=True),
        sa.Column("wifi", sa.Boolean(), nullable=True),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=250), nullable=True),
        sa.Column("file_name", sa.String(length=50), nullable=True),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("images")
    op.drop_table("amenities")
    op.drop_table("rooms")
    op.drop_table("facility_group")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_hotels_name"), table_name="hotels")
    op.drop_table("hotels")
    op.drop_table("facilities")
    op.drop_table("board_types")
    # ### end Alembic commands ###
