"""two common column repeated fixed

Revision ID: ddf1718f7f85
Revises: 952fcafcf1e1
Create Date: 2022-06-01 18:28:04.908660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf1718f7f85'
down_revision = '952fcafcf1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amenities', 'disability_friendly')
    op.drop_column('facility_group', 'air_conditioning')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility_group', sa.Column('air_conditioning', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('amenities', sa.Column('disability_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
